In [0]:
import torch 


In [0]:
def activation(x):
  '''
Sigmoid 

x: torch.Tensor

  '''
  return 1/(1+torch.exp(-x))

In [0]:
#Generate dummy data

torch.manual_seed(7)

features = torch.randn((1,5)) #input

weights = torch.randn_like(features) #weights are derived from features

bias = torch.randn((1,1))


In [21]:
print(torch.mm(features,weights.T)) # .T for transpose same as in numpy
#perceptron

y_hat = activation(torch.sum(features * weights) + bias) # * operator for element-wise muliplication (Hadamard product) 
print(y_hat)

print(activation(torch.mm(features,weights.T)+bias))


tensor([[-1.9796]])
tensor([[0.1595]])
tensor([[0.1595]])
