In [0]:
import torch 


In [0]:
def activation(x):
  '''
Sigmoid 

x: torch.Tensor

  '''
  return 1/(1+torch.exp(-x))

In [0]:
#Generate dummy data

torch.manual_seed(7)

features = torch.randn((1,5)) #input

weights = torch.randn_like(features) #weights are derived from features

bias = torch.randn((1,1))


In [0]:
print(torch.mm(features,weights.T)) # .T for transpose same as in numpy
#perceptron

y_hat = activation(torch.sum(features * weights) + bias) # * operator for element-wise muliplication (Hadamard product) 
print(y_hat)

print(activation(torch.mm(features,weights.T)+bias))


tensor([[-1.9796]])
tensor([[0.1595]])
tensor([[0.1595]])


In [0]:
# multilayer

features = torch.randn((1,3))

hidden =2


In [0]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [0]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [2]:


dtype = torch.float
device = torch.device("cpu")
# device = torch.device("cuda:0") # Uncomment this to run on GPU

# N is batch size; D_in is input dimension;
# H is hidden dimension; D_out is output dimension.
N, D_in, H, D_out = 64, 1000, 100, 10

# Create random input and output data
x = torch.randn(N, D_in, device=device, dtype=dtype)
y = torch.randn(N, D_out, device=device, dtype=dtype)

# Randomly initialize weights
w1 = torch.randn(D_in, H, device=device, dtype=dtype)
w2 = torch.randn(H, D_out, device=device, dtype=dtype)

learning_rate = 1e-6
for t in range(500):
    # Forward pass: compute predicted y
    h = x.mm(w1)
    h_relu = h.clamp(min=0)
    y_pred = h_relu.mm(w2)

    # Compute and print loss
    loss = (y_pred - y).pow(2).sum().item()
    if t % 100 == 99:
        print(t, loss)

    # Backprop to compute gradients of w1 and w2 with respect to loss
    grad_y_pred = 2.0 * (y_pred - y)
    grad_w2 = h_relu.t().mm(grad_y_pred)
    grad_h_relu = grad_y_pred.mm(w2.t())
    grad_h = grad_h_relu.clone()
    grad_h[h < 0] = 0
    grad_w1 = x.t().mm(grad_h)

    # Update weights using gradient descent
    w1 -= learning_rate * grad_w1
    w2 -= learning_rate * grad_w2

99 359.89532470703125
199 0.7768354415893555
299 0.0023894943296909332
399 8.055055513978004e-05
499 1.9387622160138562e-05
